version: "3"

networks:
  postgresnet:

services:
  postgresql:  
    restart: on-failure
    image: postgres:9.6 
    hostname: postgresql
    container_name: postgresql
    environment:                                                            
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=projectdb  
    networks:
      - postgresnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask:
    restart: on-failure
    build: .
    container_name: flask
    volumes: 
      - .:/aplication
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    networks:                                                               
      - postgresnet   

volumes:
  postgres-data: